LA.UI/Models/ErrorViewModel.cs
namespace LA.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LA.UI/Controllers/ConceptsController.cs
using Microsoft.AspNetCore.Mvc;

namespace LA.UI.Controllers
{
    public class ConceptsController : Controller
    {
        public IActionResult Index()
        {
            //ViewBag.Message = "Hello from ViewBag";
            //ViewData["Message"] = "Hello from ViewData";
            TempData["Message"] = "Hello from Tempdata..!";
            return View();
        }

        public IActionResult NextPage()
        {
            string message = TempData["Message"].ToString();
            return View("NextPage", message);
        }
    }
}

LA.UI/Controllers/CountryController.cs
using LA.Models;
using LA.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LA.UI.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICountryRepo _countryRepo;

        public CountryController(ICountryRepo countryRepo)
        {
            _countryRepo = countryRepo;
        }

        public IActionResult Index()
        {
            var countryList = _countryRepo.GetAll();
            return View(countryList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Country country)
        {
            _countryRepo.Save(country);
           return  RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var country = _countryRepo.GetById(id);
            return View(country);
        }

        [HttpPost]
        public IActionResult Edit(Country country)
        {
            _countryRepo.Edit(country);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var country = _countryRepo.GetById(id);
            _countryRepo.RemoveData(country);
            return RedirectToAction("Index");
        }
    }
}

LA.UI/Controllers/DistrictController.cs
using LA.Models;
using LA.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LA.UI.Controllers
{
    public class DistrictController : Controller
    {
        private readonly IStateRepo _stateRepo;
        private readonly IDistrictRepo _districtRepo;

        public DistrictController(IStateRepo stateRepo, IDistrictRepo districtRepo)
        {
            _stateRepo = stateRepo;
            _districtRepo = districtRepo;
        }

        public IActionResult Index()
        {
            var districts = _districtRepo.GetAll();
            return View(districts);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var stateList = _stateRepo.GetAll();
            ViewBag.StateList = new SelectList(stateList, "ID", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(District district)
        {
            _districtRepo.Save(district);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id) {
            var stateList = _stateRepo.GetAll();
            ViewBag.StateList = new SelectList(stateList, "ID", "Name");

            var district = _districtRepo.GetById(id);
            return View(district);
        }

        [HttpPost]
        public IActionResult Edit(District district)
        {
            _districtRepo.Edit(district);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var district = _districtRepo.GetById(id);
            _districtRepo.RemoveData(district);
            return RedirectToAction("Index");
        }

    }
}

LA.UI/Controllers/HomeController.cs
using LA.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LA.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LA.UI/Controllers/StateController.cs
using LA.Models;
using LA.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LA.UI.Controllers
{
    public class StateController : Controller
    {
        private readonly ICountryRepo _countryRepo;
        private readonly IStateRepo _stateRepo;

        public StateController(ICountryRepo countryRepo, IStateRepo stateRepo)
        {
            _countryRepo = countryRepo;
            _stateRepo = stateRepo;
        }

        public IActionResult Index()
        {
            var states = _stateRepo.GetAll();
            return View(states);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var countryList = _countryRepo.GetAll();
            ViewBag.CountryList = new SelectList(countryList, "ID", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(State state)
        {
            _stateRepo.Save(state);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id) {
            var countryList = _countryRepo.GetAll();
            ViewBag.CountryList = new SelectList(countryList, "ID", "Name");

            var state = _stateRepo.GetById(id);
            return View(state);
        }

        [HttpPost]
        public IActionResult Edit(State state)
        {
            _stateRepo.Edit(state);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var state = _stateRepo.GetById(id);
            _stateRepo.RemoveData(state);
            return RedirectToAction("Index");
        }
    }
}

LA.UI/Views/Concepts/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@* <h3>@ViewBag.Message</h3> *@
<h3>@ViewData["Message"]</h3>

LA.UI/Views/Concepts/NextPage.cshtml
@model string
@{
    ViewData["Title"] = "NextPage";
}

<h1>@Model</h1>

LA.UI/Views/Country/Create.cshtml
@model LA.Models.Country

@{
    ViewData["Title"] = "Create";
}

<h1>Add new Country</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control my-2" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary my-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LA.UI/Views/Country/Edit.cshtml
@model LA.Models.Country

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Country</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
               
                <input type="hidden" asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control my-2" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary my-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LA.UI/Views/Country/Index.cshtml
@model IEnumerable<LA.Models.Country>

@{
    ViewData["Title"] = "Index";
}

<h1>Country List</h1>

<p>
    <a class="btn btn-info" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
}
    </tbody>
</table>

LA.UI/Views/District/Create.cshtml
@model LA.Models.District

@{
    ViewData["Title"] = "Create";
}

<h1>Add New District</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control my-2" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StateID" class="control-label"></label>
                <select asp-for="StateID" asp-items="@ViewBag.StateList" class="form-control my-2">
                    <option selected disabled>Select State</option>
                </select>
                <span asp-validation-for="StateID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary my-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

LA.UI/Views/District/Edit.cshtml
@model LA.Models.District

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit District</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                
                <input type="hidden" asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control my-2" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StateID" class="control-label"></label>
                <select asp-for="StateID" asp-items="@ViewBag.StateList" class="form-control my-2">
                    <option selected disabled>Select State</option>
                </select>
                <span asp-validation-for="StateID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary my-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

LA.UI/Views/District/Index.cshtml
@model IEnumerable<LA.Models.District>

@{
    ViewData["Title"] = "Index";
}

<h1>District List</h1>

<p>
    <a class="btn btn-info" asp-action="Create">Add New District</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                State
            </th>
            <th>
                Country
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State.Name)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.State.Country.Name)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
               
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
}
    </tbody>
</table>

LA.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LA.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LA.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LA.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Manage Countries</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="State" asp-action="Index">Manage States</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="District" asp-action="Index">Manage Districts</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - LA.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LA.UI/Views/State/Create.cshtml
@model LA.Models.State

@{
    ViewData["Title"] = "Create";
}

<h1>Add New State</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control my-2" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryID" class="control-label"></label>
                <select asp-for="CountryID" asp-items="@ViewBag.CountryList" class="form-control my-2">
                    <option selected disabled>Select Country</option>
                </select>
                <span asp-validation-for="CountryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary my-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

LA.UI/Views/State/Edit.cshtml
@model LA.Models.State

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit State</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
               
                <input type="hidden" asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control my-2" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryID" class="control-label"></label>
                <select asp-for="CountryID" asp-items="@ViewBag.CountryList" class="form-control my-2">
                    <option selected disabled>Select Country</option>
                </select>
                <span asp-validation-for="CountryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary my-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

LA.UI/Views/State/Index.cshtml
@model IEnumerable<LA.Models.State>

@{
    ViewData["Title"] = "Index";
}

<h1>State List</h1>

<p>
    <a class="btn btn-info" asp-action="Create">Add New State</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Country
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
}
    </tbody>
</table>